tfa-bot and tfa-bot-slim tested

diff --git a/tfa-bot-slim/Dockerfile b/tfa-bot-slim/Dockerfile
--- a/tfa-bot-slim/Dockerfile
+++ b/tfa-bot-slim/Dockerfile
@@ -1,17 +1,17 @@
 # Create an image to hold the build process
-FROM mono:latest AS build
+FROM mono:5.16.0.179 AS build
 
 ARG SIPP_BRANCH="v3.5.2"
 ARG BOT_BRANCH="master"
 
 WORKDIR /app
 
+# Update package lists and install build dependencies
 RUN set -xe \
-\
-  # Update package lists and install build dependencies
   && apt-get update \
-	&& apt-get -y install \
+	&& apt-get --no-install-recommends -y install \
     autoconf \
+    automake \
     build-essential \
     git \
     iputils-ping \
@@ -21,16 +21,19 @@ RUN set -xe \
     locales-all \
     net-tools \
     ssh \
-    wget \
-\
-  # Additional dependency installation
+    wget
+
+# Additional dependency installation
+RUN set -xe \
   && git clone --branch ${SIPP_BRANCH} https://github.com/SIPp/sipp.git \
-  && wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe \
-\
-  # Clone the bot repo
-  && git clone -b ${BOT_BRANCH} https://git.factoid.org/TFA/TFA-Bot.git \
-\
-  # Build the bot
+  && wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
+
+# Clone the bot repo
+RUN set -xe \
+  && git clone -b ${BOT_BRANCH} https://git.factoid.org/TFA/TFA-Bot.git
+
+# Build the bot
+RUN set -xe \
   && cd sipp \
   && ./build.sh \
   && cd ../TFA-Bot \
@@ -38,17 +41,16 @@ RUN set -xe \
   && msbuild -p:Configuration=Release -property:GitCommit=$(git rev-parse HEAD) TFA-Bot.sln
 
 # Create an image for the runtime
-FROM mono:slim
+FROM mono:5.16.0.179-slim
 
 ENV TZ=UTC
 
 WORKDIR /app
 
+# Update package lists, install runtime dependencies, and clean up
 RUN set -xe \
-\
-  # Update package lists and install runtime dependencies
   && apt-get update \
-	&& apt-get -y install \
+	&& apt-get --no-install-recommends -y install \
     iputils-ping \
     libmono-system-net-http4.0-cil \
     libmono-system-runtime4.0-cil \
@@ -58,13 +60,12 @@ RUN set -xe \
     libncursesw5-dev \
     mtr-tiny \
     net-tools \
-\
-  # Clean up after the package installation
   && apt-get autoremove --purge \
   && apt-get clean \
-  && rm -rf /var/lib/apt/lists/* \
-\
-  # Configure timezone
+  && rm -rf /var/lib/apt/lists/*
+
+# Configure timezone
+RUN set -xe \
   && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime
 
 # Copy build artifacts from the build image
diff --git a/tfa-bot/Dockerfile b/tfa-bot/Dockerfile
--- a/tfa-bot/Dockerfile
+++ b/tfa-bot/Dockerfile
@@ -1,4 +1,4 @@
-FROM mono:latest AS build
+FROM mono:5.16.0.179 AS build
 
 ARG SIPP_BRANCH="v3.5.2"
 ARG BOT_BRANCH="master"
@@ -7,48 +7,51 @@ ENV TZ=UTC
 
 WORKDIR /app
 
+# Update package lists, install build and runtime packages, and clean up
 RUN set -xe \
-\
-  # Update package lists and install build and runtime dependencies
   && apt-get update \
-	&& apt-get -y install \
+	&& apt-get --no-install-recommends -y install \
     autoconf \
+    automake \
     build-essential \
     git \
     iputils-ping \
-    mtr-tiny \
-    net-tools \
     libncurses5-dev \
     libncursesw5-dev \
     locales \
     locales-all \
+    mtr-tiny \
     net-tools \
     ssh \
     wget \
-\
-  # Additional dependency installation
+  && apt-get autoremove --purge \
+  && apt-get clean \
+  && rm -rf /var/lib/apt/lists/*
+
+# Additional dependency installation
+RUN set -xe \
   && git clone --branch ${SIPP_BRANCH} https://github.com/SIPp/sipp.git \
-  && wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe \
-\
-  # Clone the bot repo
-  && git clone -b ${BOT_BRANCH} https://git.factoid.org/TFA/TFA-Bot.git \
-\
-  # Build the bot
+  && wget https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
+
+# Clone the bot repo
+RUN set -xe \
+  && git clone -b ${BOT_BRANCH} https://git.factoid.org/TFA/TFA-Bot.git
+
+# Build the bot
+RUN set -xe \
   && cd sipp \
   && ./build.sh \
   && cd ../TFA-Bot \
   && mono ../nuget.exe restore TFA-Bot.sln \
-  && msbuild -p:Configuration=Release -property:GitCommit=$(git rev-parse HEAD) TFA-Bot.sln \
-\
-  # Clean up after the build
-  && apt-get autoremove --purge \
-  && apt-get clean \
-  && rm -rf /var/lib/apt/lists/* \
-\
-  # Post-build configuration
+  && msbuild -p:Configuration=Release -property:GitCommit=$(git rev-parse HEAD) TFA-Bot.sln
+
+# Post-build configuration
+RUN set -xe \
   && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
-  && chmod +x ./entrypoint.sh \
-  && ln -s ./entrypoint.sh /
+  && cp ./TFA-Bot/entrypoint.sh / \
+  && chmod +x /entrypoint.sh
+
+WORKDIR /
 
 ENTRYPOINT ["/entrypoint.sh"]
 
